### ISSUE TITLE
카테고리별 조회 페이지 만들기

### ISSUE THREAD

**Issue by hwangstar156** [woowacourse-teams/2022-gong-seek#113]
## 기능 명세
 - [x] 에러 카테고리 조회하는 페이지 UI 그리기
 - [x] 토론 카테고리 조회하는 페이지 UI 그리기
 - [x] 게시글 클릭시 상세게시물로 이동하는 기능
 - [x] 정렬기준 드롭다운 UI 만들기
 - [ ] 무한 스크롤 구현하기
## 예상 시간
2022.07.20

**Comment by liswktjs** [comment]
스밍 이슈 만들때 라벨좀 달아주세요~~
